# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10 

In [2]:
b2 = np.zeros(10)
print(b2)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3. Create a vector with values ranging from 10 to 49

In [3]:
b3 = np.arange(10,50)
print(b3)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


4. Find the shape of previous array in question 3

In [4]:
print(b3.shape)

(40,)


5. Print the type of the previous array in question 3

In [5]:
print(b3.dtype)

int32


6. Print the numpy version and the configuration


In [6]:
print("numPy version = ",np.__version__)
print("numPy Configration = ",np.show_config())

numPy version =  1.18.1
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/ProgramData/Anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.1

7. Print the dimension of the array in question 3


In [7]:
print(b3.ndim)

1


8. Create a boolean array with all the True values

In [8]:
b8 = np.ones((5), dtype=bool)
b8

array([ True,  True,  True,  True,  True])

9. Create a two dimensional array




In [9]:
b9 = np.ndarray((2,2),dtype=bool)
b9

array([[ True, False],
       [False, False]])

10. Create a three dimensional array



In [10]:
ten = np.zeros((2, 2, 2))
ten

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [11]:
e1 = np.arange(0,10)
print(e1)
e1s = e1[::-1]
print(e1s)

[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]


12. Create a null vector of size 10 but the fifth value which is 1 

In [12]:
e12 = np.zeros(10)
print(e12)
e12[4] = 1
print(e12)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


13. Create a 3x3 identity matrix

In [13]:
e13 = np.eye(3)
print(e13)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [14]:
arr = np.array([1, 2, 3, 4, 5])
float_arr = arr.astype(np.float64)
print(float_arr)

[1. 2. 3. 4. 5.]


15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [15]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
z = arr1*arr2
print(z)

[[ 0.  8.  3.]
 [28. 10. 72.]]


16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [16]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
arr1>arr2

array([[ True, False,  True],
       [False,  True, False]])

17. Extract all odd numbers from arr with values(0-9)

In [17]:
a = np.arange(0,10)
print(a)
b= a[a % 2 == 1]
print(b)

[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


18. Replace all odd numbers to -1 from previous array

In [18]:
print(a)
a[a % 2 == 1]=-1
print(a)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [19]:
arr = np.arange(10)
print(arr)
arr[5:9]=12
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4 12 12 12 12  9]


20. Create a 2d array with 1 on the border and 0 inside

In [20]:
x = np.ones((5,5))
print(x)
x[1:-1,1:-1] = 0
print(x)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [21]:
arr2d = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9]])
print(arr2d)
arr2d[1:2,1:2]=12
print(arr2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [ 4 12  6]
 [ 7  8  9]]


22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [22]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr3d)
arr3d[0][0] = 64
print(arr3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[[64 64 64]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [24]:
array1 = np.arange(10).reshape(2,5)
print(array1)
print(array1[0])

[[0 1 2 3 4]
 [5 6 7 8 9]]
[0 1 2 3 4]


24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [25]:
array1 = np.arange(10).reshape(2,5)
print(array1)
print(array1[1][1])

[[0 1 2 3 4]
 [5 6 7 8 9]]
6


25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [26]:
array1 = np.arange(9).reshape(3,3)
print(array1)
print(array1[0:2,2:4])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[2]
 [5]]


26. Create a 10x10 array with random values and find the minimum and maximum values

In [27]:
arr = np.random.randn(10,10)
print(arr)
print("min Value = ", np.min(arr))
print("max Value = ", np.max(arr))

[[-0.2815367  -0.22325241 -0.37282286  0.97770606  1.83735556  2.04207426
  -0.32545852  0.7968874  -0.14731877 -0.25121245]
 [ 0.68412658 -0.80080831  0.55966399 -2.0320371   2.47093224 -1.12634216
   0.31453094 -0.28531066 -0.05097508 -0.32378781]
 [-0.50208453  0.18649487  1.49000295  0.41769421 -0.46070233  0.2212051
  -1.16306936 -0.68454324  0.82887462  1.2201123 ]
 [-0.12268259 -1.79651813  1.04505154  0.25651164  0.45437606  0.23960753
  -0.50869926 -0.75422049 -1.60733184  0.24865208]
 [-0.12254732  0.5492142  -0.17778629 -1.05373849 -0.11421358 -0.69928946
  -0.83989061  0.02915992 -1.26392846  1.01205806]
 [-0.61430019  0.24024642 -1.03758705  1.119294   -0.06880418 -0.4303077
  -0.3409596  -0.65774645 -0.33998901 -1.10811677]
 [ 0.83187587  0.22874847 -0.43150333 -0.81872052 -0.86967825  0.11450274
  -1.37289266  0.73397628  1.20860679  0.58703925]
 [-1.365576    0.27970778 -0.62730681 -0.25697765  0.49121161  0.27678046
   1.34703894  0.80096109  0.5432603  -0.63089474]
 [

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [28]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
print("common = " , np.intersect1d(a, b))
print(a==b)

common =  [2 4]
[False  True False  True False  True False  True False False]


28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [29]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [30]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
print("Names = ")
print(names)
print("")
print("Data = ")
print(data)
print("")
print("Array data where the values from array names are not equal to Will")
print(data[names != 'Will'])

Names = 
['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']

Data = 
[[-0.19206747  1.12574492 -0.67231883  0.33929757]
 [-0.43567639  1.45864993  0.78452293 -1.57089022]
 [-0.27258258 -2.27894501  0.98979028  0.96071445]
 [ 2.92813708 -0.96203148  2.14093725 -0.78846022]
 [ 0.5358891   0.27420115 -0.47254445 -0.1283015 ]
 [-1.18107841 -0.36168717 -0.58388001 -1.23522464]
 [-0.4417868   0.7378053  -1.3087646  -2.31044149]]

Array data where the values from array names are not equal to Will
[[-0.19206747  1.12574492 -0.67231883  0.33929757]
 [-0.43567639  1.45864993  0.78452293 -1.57089022]
 [ 2.92813708 -0.96203148  2.14093725 -0.78846022]
 [-1.18107841 -0.36168717 -0.58388001 -1.23522464]
 [-0.4417868   0.7378053  -1.3087646  -2.31044149]]


30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [31]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
print("Names = ")
print(names)
print("")
print("Data = ")
print(data)
print("")
print("Array data where the values from array names are not equal to Will and JOE")
print(data[(names != 'Will') & (names != 'Joe')])

Names = 
['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']

Data = 
[[ 0.35019998 -0.89033996 -0.26067304  0.77883714]
 [-0.02300681  0.38971775 -0.05780999  1.47313434]
 [-0.687914    1.00849065 -0.29008709 -0.20809766]
 [ 0.88143524  1.32383414  0.03703372  2.15458154]
 [ 0.21076552 -0.15030226 -0.47865397 -0.88868355]
 [ 1.39075753 -0.49464637 -0.57729544  0.76037348]
 [ 0.89032427 -0.48877079 -1.97194927 -0.29491866]]

Array data where the values from array names are not equal to Will and JOE
[[ 0.35019998 -0.89033996 -0.26067304  0.77883714]
 [ 0.88143524  1.32383414  0.03703372  2.15458154]]


Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [32]:
array1 = (np.arange(1,16).reshape(5,3)).astype(np.float64)
print(array1)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]
 [13. 14. 15.]]


32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [33]:
array1 = (np.arange(1,17).reshape(2,2,4)).astype(np.float64)
print(array1)

[[[ 1.  2.  3.  4.]
  [ 5.  6.  7.  8.]]

 [[ 9. 10. 11. 12.]
  [13. 14. 15. 16.]]]


33. Swap axes of the array you created in Question 32

In [34]:
print(array1)
np.swapaxes(array1,0,1)

[[[ 1.  2.  3.  4.]
  [ 5.  6.  7.  8.]]

 [[ 9. 10. 11. 12.]
  [13. 14. 15. 16.]]]


array([[[ 1.,  2.,  3.,  4.],
        [ 9., 10., 11., 12.]],

       [[ 5.,  6.,  7.,  8.],
        [13., 14., 15., 16.]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [35]:
r = np.arange(0,1,.1)
r1 = np.sqrt(r)
r3=np.where(r1<0.5,0,r1)
print(r1)
print(r)
print(r3)

[0.         0.31622777 0.4472136  0.54772256 0.63245553 0.70710678
 0.77459667 0.83666003 0.89442719 0.9486833 ]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
[0.         0.         0.         0.54772256 0.63245553 0.70710678
 0.77459667 0.83666003 0.89442719 0.9486833 ]


35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [36]:
a = np.random.randn(12)
b = np.random.randn(12)
c = np.maximum(a,b)
print(a)
print(b)
print(c)

[ 1.02456853  0.25504814  0.41160136 -0.26620138 -0.52595643 -1.55661888
  0.13313242 -1.53467322 -0.10555004  0.21763948  1.19208668 -1.2113695 ]
[ 1.66816771 -1.10760206  0.24588736 -0.47455135 -0.02848733  1.23935224
  1.30298471 -2.36475465  0.00926735  0.14364605 -0.95306192  0.89669819]
[ 1.66816771  0.25504814  0.41160136 -0.26620138 -0.02848733  1.23935224
  1.30298471 -1.53467322  0.00926735  0.21763948  1.19208668  0.89669819]


36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [37]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
print(names)
unames=np.sort(np.unique(names))
print(unames)

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
['Bob' 'Joe' 'Will']


37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [38]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
print(a)
print(b)
result = np.setdiff1d(a, b)
print(result)

[1 2 3 4 5]
[5 6 7 8 9]
[1 2 3 4]


38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [39]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])
print(sampleArray)
sampleArray = np.delete(sampleArray , 1, axis = 1) 
sampleArray = np.insert(sampleArray , 1, newColumn, axis = 1) 
print (sampleArray)

[[34 43 73]
 [82 22 12]
 [53 94 66]]
[[34 10 73]
 [82 10 12]
 [53 10 66]]


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [40]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
print(x)
print(y)
np.dot(x, y)

[[1. 2. 3.]
 [4. 5. 6.]]
[[ 6. 23.]
 [-1.  7.]
 [ 8.  9.]]


array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [41]:
x = np.random.randn(20)
print(x)
y = np.cumsum(x)
print(y)

[-0.1675482   1.04162469  0.57714209 -0.84334453  0.49639667 -1.09629011
 -0.52231449 -1.23616832  1.75157093  0.39102141 -2.04184894  1.323795
  1.80357968  0.85654529 -0.06871935 -0.14301499  1.73903768  1.02446151
 -0.42178226  0.59291197]
[-1.67548201e-01  8.74076489e-01  1.45121858e+00  6.07874050e-01
  1.10427072e+00  7.98061195e-03 -5.14333882e-01 -1.75050220e+00
  1.06872728e-03  3.92090141e-01 -1.64975880e+00 -3.25963803e-01
  1.47761588e+00  2.33416116e+00  2.26544181e+00  2.12242682e+00
  3.86146451e+00  4.88592602e+00  4.46414376e+00  5.05705573e+00]
